spring.application.name=server

server.port=8080

# === Logging Configuration ===
logging.level.root=INFO
logging.level.com.mimosa=INFO
# Path to the log file (will be generated in server/logs/)
logging.file.name=logs/server.log

# Log format for console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Log format for file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

